### ISSUE TITLE
Seg fault generated in findSafestPath

### ISSUE THREAD

**Issue by yapa5475** [dara1429/Rapacchietta_CSCI2270_FinalProject#1]
I was met with a segmentation fault when in the findSafestPath function. I found that the rooms were initialized correctly, but the for loop following that (which checks if the room found is the exit), something is causing the seg fault.

**Comment by dara1429** [comment]
Are you using the included maze.txt file or your own? I cant seem to replicate the segfault. If you are using your own can you post it.

**Comment by dara1429** [comment]
Ok i looked into it and i think i solved the issue. It seems compiling the standard way produces the segmentation fault (Not sure why). I have updated the repo files and added a make file. I also added instructions on how to compile using it. Let me know if it works.
